exports.ACTIONS = {
    ADD_GASTO: "addGasto",
    ADD_CATEGORIA: "addCategoria",
    EDIT_GASTO: "editGasto",
    GASTO_UPDATE_AMOUNT: "gastoUpdateAmount",
    GASTO_UPDATE_DATE: "gastoUpdateDate",
    DELETE_GASTO: "deleteGasto",
    ADD_NOTIFICATION: "addNotification",
    GET_NOTIFICATIONS: "getNotifications",
    DELETE_NOTIFICATION: "deleteNotification",
    ADD_SUBSCRIPTION: "addSubscription",
    EDIT_SUBSCRIPTION: "editSubscription",
    SUBSCRIPTION_UPDATE_AMOUNT: "subscriptionUpdateAmount",
    SUBSCRIPTION_UPDATE_DATE: "subscriptionUpdateDate",
}